name: docs CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}



    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Charles

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8


      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme

      - name: make the sphinx docs
        run: |
          cd docs/
          make -C docs clean
          make -C docs html

      - name: Init new repo in dist folder and commit
        run: |
          cd docs/build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: documentation
          force: true
          directory: ./docs/build/html

